version: '3.9'

services:
  coreapi:
    image: image_schedule_api 
    container_name: container_schedule_api
    build:
      context: .
      dockerfile: CoreAPI/Dockerfile
    depends_on: 
      - "postgres"
      - "web-ui"
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:9091;http://+:9090
      - ASPNETCORE_Kestrel__Certificates__Default__Password=0900
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore-localhost-D9F2EF68C8B1B76FC864F2421A2F783590B50ADA.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  postgres:
    container_name: postgres_container
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0900"
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
       - './postgres-data:/var/lib/postgresql/data'
    ports:
      - "5433:5432"
    restart: unless-stopped
  web-ui:
    image: image_schedule_webui
    build: 
      context: ./WebUI
      dockerfile: Dockerfile
    container_name: container_schedule_webui
    ports:
      - "8080:80"
